### ISSUE TITLE
Date Header 2px missing

### ISSUE THREAD

**Issue by sebasira** [sebasira/jquery.schedule.plus#12]
Related to #1.

When working with Bootstrap, the date header of the timeline is 2px smaller than it should be (in width) and I do not know why. If there are multiple dates displayed this delta propagates and the impression in bigger in the following dates because the header width does not match the timeline width.

  Here's a picture of that:
<img width="320" alt="Screen Shot 2024-03-29 at 10 20 39" src="https://github.com/sebasira/jquery.schedule.plus/assets/11217669/16b0955d-084a-4139-87e7-7968d85386f9">

For example for the display configured in 1hour time-slot, the width of the header should be **1440px** and it is **1438px**

**Comment by personalyisus** [comment]
@sebasira  is the space between them what you need to get rid of? Your divs are having their correct size, it's just that the calculations get done so 1440px = 1438px of the div **plus** 2 pixels on each side because of the border it has (since the [box-sizing](https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing) property is set to content-box as per default)

<img width="1324" alt="image" src="https://github.com/sebasira/jquery.schedule.plus/assets/8424597/cc94a9e1-6760-48ad-ae45-8cb7e1bb69f4">

For the white spaces you can just override the border property for those elements, but because whatever library you're using to generate the calendar uses inline styles on the tag you'd have to use javascript to override the width if you wanted to make them wider

Then again you'd have to tinker with css and inline styles a lot of you wanted everything to match nicely

Edit: Additionally, if you want to keep the white spaces but it's just that things are not aligned for you, I couldn't tell you why since I cannot reproduce the issue, looks ok on my local 
<img width="587" alt="image" src="https://github.com/sebasira/jquery.schedule.plus/assets/8424597/92914ebe-3937-4673-9995-84bd47792b41">

**Comment by sebasira** [comment]
@personalyisus thanks for your input! The demo should work ok. 

I'm using this library in a project that has Bootstrap 3 and I think that bootstrap adds "some thing" that mess around with the calculations... I already needed to make some adjustment as in #1.

 I'll try to look a litter deeper into this, to see if I can see any difference between the demo and the project with bootstrap

**Comment by sebasira** [comment]
Well... I've found it!

It was again the `box-sizing`. The **sc_date** must also have `box-sizing: content-box`, as the other classes in #1

**Comment by personalyisus** [comment]
Great news (: Keep at it!
